CREATE TABLE Users(userID SERIAL,userName TEXT,email TEXT UNIQUE,password TEXT,rating REAL DEFAULT 0,PRIMARY KEY(userID));
CREATE TABLE Recipes(recipeID SERIAL,chefID INTEGER NOT NULL,recipeName TEXT,foodType TEXT,pictureUrl TEXT,ingredients TEXT[],protein REAL,carbs REAL,fat REAL,sugars REAL,PRIMARY KEY(recipeID),FOREIGN KEY (chefID) REFERENCES Users ON DELETE CASCADE);
CREATE TABLE Bookmarks(userID INTEGER,recipeID INTEGER,PRIMARY KEY(userID, recipeID),FOREIGN KEY (userID) REFERENCES Users ON DELETE CASCADE,FOREIGN KEY (recipeID) REFERENCES Recipes ON DELETE CASCADE);
INSERT INTO Users(userName,email,password) VALUES ('Paul Rice','paul.rice@gmail.com',md5('4%?~N(yPOws#9I`)}A^;{'));
INSERT INTO Users(userName,email,password) VALUES ('Lillie Dobbins','lillie.dobbins@gmail.com',md5('N<}-^zCcISgQP>Lu4@qBYF'));
INSERT INTO Users(userName,email,password) VALUES ('Charles Sieving','charles.sieving@gmail.com',md5('c&TWsjv!>N+5k.m<frY/3]'));
INSERT INTO Users(userName,email,password) VALUES ('Emilio Morris','emilio.morris@gmail.com',md5('e6LV-C](p.yl$IGXfZQkM?'));
INSERT INTO Users(userName,email,password) VALUES ('Marlene Plymel','marlene.plymel@gmail.com',md5('?o{0Z[DXMdNk`#Lj~wpbUW'));
INSERT INTO Users(userName,email,password) VALUES ('John Holley','john.holley@gmail.com',md5('4%&ZTmg,|fdXw*/bk3ILq'));
INSERT INTO Users(userName,email,password) VALUES ('Devon Stamey','devon.stamey@gmail.com',md5('t%6x:f\mcyMGg=+(h0dz)P'));
INSERT INTO Users(userName,email,password) VALUES ('Debra Sanders','debra.sanders@gmail.com',md5('FwRj<rJY/(:&2}]$bPav.'));
INSERT INTO Users(userName,email,password) VALUES ('Doreen Bell','doreen.bell@gmail.com',md5('GwxclD3:,W{[I5zC_-0!F'));
INSERT INTO Users(userName,email,password) VALUES ('Andrew Criswell','andrew.criswell@gmail.com',md5('l5p]^uN4C_9E-*!B18YLw>'));
INSERT INTO Users(userName,email,password) VALUES ('Adam Obermiller','adam.obermiller@gmail.com',md5('X9[Y36$Sr}~4%Kj-,Hl>O'));
INSERT INTO Users(userName,email,password) VALUES ('Joseph Kiser','joseph.kiser@gmail.com',md5('tRIs#[4rT*,OiC2-=xGEp'));
INSERT INTO Users(userName,email,password) VALUES ('Mack Bailey','mack.bailey@gmail.com',md5('5@rsUf%]#{Bb0Kvi)}TNO'));
INSERT INTO Users(userName,email,password) VALUES ('Elizabeth Garlock','elizabeth.garlock@gmail.com',md5('Y7:#|a=Ws&p?Te.UMn;%cm'));
INSERT INTO Users(userName,email,password) VALUES ('Derek Choudhury','derek.choudhury@gmail.com',md5('W1/Mm9dJX,8%s.TlYHaS[R'));
INSERT INTO Users(userName,email,password) VALUES ('Tiffany Schmucker','tiffany.schmucker@gmail.com',md5('/t+Rye){&Ub_DN=G-6(h@5'));
INSERT INTO Users(userName,email,password) VALUES ('Virginia Holleran','virginia.holleran@gmail.com',md5('[p)V3?cP$#:uR;lO<Zd(+'));
INSERT INTO Users(userName,email,password) VALUES ('Jessica Root','jessica.root@gmail.com',md5('mvCH4W*D_<y[]-YxMAKag'));
INSERT INTO Users(userName,email,password) VALUES ('Paul Mccormick','paul.mccormick@gmail.com',md5('qS,UK+X.O5[FJwGNLx-tIZ'));
INSERT INTO Users(userName,email,password) VALUES ('Calvin Mohammad','calvin.mohammad@gmail.com',md5('oni)=hk}2d8U9\&[;.L%_E'));
INSERT INTO Users(userName,email,password) VALUES ('Adolfo Russell','adolfo.russell@gmail.com',md5('jwXNU@~s2rz{4I,b!*eM%'));
INSERT INTO Users(userName,email,password) VALUES ('Claire Erickson','claire.erickson@gmail.com',md5('y3HW{)#/O|4T7@-&Y+n^v'));
INSERT INTO Users(userName,email,password) VALUES ('Damon Williams','damon.williams@gmail.com',md5('v4Tr*I6l-=5mV_P3><ZB].'));
INSERT INTO Users(userName,email,password) VALUES ('James White','james.white@gmail.com',md5('@,GTH~s.g>nlLr:y\^}(f#'));
INSERT INTO Users(userName,email,password) VALUES ('Patricia Bukovsky','patricia.bukovsky@gmail.com',md5('O[eMZ)#x~gsCo`:|<A\YVU'));
INSERT INTO Users(userName,email,password) VALUES ('Earnest Allen','earnest.allen@gmail.com',md5('dW.2wy`$/9>=1c@[?eP3+T'));
INSERT INTO Users(userName,email,password) VALUES ('Lisa Woodruff','lisa.woodruff@gmail.com',md5('u3tSz2`E<0%_M/ZPI]?|o'));
INSERT INTO Users(userName,email,password) VALUES ('Margaret Brumit','margaret.brumit@gmail.com',md5('A4mzBbauFfo(6%?r8LGT$j'));
INSERT INTO Users(userName,email,password) VALUES ('Anthony Rancourt','anthony.rancourt@gmail.com',md5('ev?5&o@U:pb+VP=W4r7RN-'));
INSERT INTO Users(userName,email,password) VALUES ('Maria Darwin','maria.darwin@gmail.com',md5('c>!?=y;un<~3/5%NB$l0*-'));
INSERT INTO Users(userName,email,password) VALUES ('Tracey Gomez','tracey.gomez@gmail.com',md5('?o,]}FVrYf[XZ|qATt.(^'));
INSERT INTO Users(userName,email,password) VALUES ('Jane Day','jane.day@gmail.com',md5('_[BotD@!Xpk\wh#-HC]=`Z'));
INSERT INTO Users(userName,email,password) VALUES ('David Ferreira','david.ferreira@gmail.com',md5(';d*ZTw63ju4_FGKg#U\C@n'));
INSERT INTO Users(userName,email,password) VALUES ('Tina Mclennan','tina.mclennan@gmail.com',md5('4m1=~B)2;hQoj*sTHYZDz<'));
INSERT INTO Users(userName,email,password) VALUES ('John Flores','john.flores@gmail.com',md5('Yr0Pw8x#hFqe+<~>ckB%N'));
INSERT INTO Users(userName,email,password) VALUES ('Naomi Swift','naomi.swift@gmail.com',md5('>\ub=&<AZOXfFdG}/5zT;s'));
INSERT INTO Users(userName,email,password) VALUES ('Mary Severy','mary.severy@gmail.com',md5('N^&VCn~-#+/T.IF1>J,Wu'));
INSERT INTO Users(userName,email,password) VALUES ('David Breckenridge','david.breckenridge@gmail.com',md5('S!*V^ik:Asz-,]D49}M%Y('));
INSERT INTO Users(userName,email,password) VALUES ('Roger Fulcher','roger.fulcher@gmail.com',md5('GoH&B#ngL!O[ef{8a9kj6'));
INSERT INTO Users(userName,email,password) VALUES ('Lyle Bredesen','lyle.bredesen@gmail.com',md5('FPzL[Eq*K/ut+ZOS]>=YGV'));
INSERT INTO Users(userName,email,password) VALUES ('Shirley Delgado','shirley.delgado@gmail.com',md5('oA2H#c!Y>u{1$n9d^mIWh7'));
INSERT INTO Users(userName,email,password) VALUES ('Winford Watts','winford.watts@gmail.com',md5('q)gi/Dyj<GY*wLe4K912Zf'));
INSERT INTO Users(userName,email,password) VALUES ('Reyes Gonzales','reyes.gonzales@gmail.com',md5('MVF3m04k)q`z(\-Y{oS_I'));
INSERT INTO Users(userName,email,password) VALUES ('Israel Craig','israel.craig@gmail.com',md5(')f|&o4Y/18=}<nHxR-C`~u'));
INSERT INTO Users(userName,email,password) VALUES ('Sheri Mears','sheri.mears@gmail.com',md5('GmFLVw/O%i:1~fH^So#T_K'));
INSERT INTO Users(userName,email,password) VALUES ('Alejandro Rogers','alejandro.rogers@gmail.com',md5(')-/5}(A=?y!FKht|do<Hi'));
INSERT INTO Users(userName,email,password) VALUES ('Sydney Bolton','sydney.bolton@gmail.com',md5('[>97S&;*o%T}.g#1X2Inz'));
INSERT INTO Users(userName,email,password) VALUES ('Heidi Cadwallader','heidi.cadwallader@gmail.com',md5('68U=RFa<5B-,&1G40]CMqJ'));
INSERT INTO Users(userName,email,password) VALUES ('Linda Hood','linda.hood@gmail.com',md5('x5>AMO4)-SK@lZhFkt^PNC'));
INSERT INTO Users(userName,email,password) VALUES ('Stuart Klein','stuart.klein@gmail.com',md5('.(w:=|lHLR]vtm0Ed45aj*'));
INSERT INTO Users(userName,email,password) VALUES ('Kenneth Potter','kenneth.potter@gmail.com',md5('lQJUq7\^oB]x)Ibhu-6rE;'));
INSERT INTO Users(userName,email,password) VALUES ('Joseph Boyer','joseph.boyer@gmail.com',md5('$=HX~T%{t;vWy5kr*wgQ7I'));
INSERT INTO Users(userName,email,password) VALUES ('Amy Bates','amy.bates@gmail.com',md5('sBA$U}~dW<T*>ubf28#mop'));
INSERT INTO Users(userName,email,password) VALUES ('Janice Pulido','janice.pulido@gmail.com',md5('yz!.XlhT+^q9>d4}C]$5<'));
INSERT INTO Users(userName,email,password) VALUES ('John Bowling','john.bowling@gmail.com',md5('\9m^LTaSg`,|b~vi{X.xC8'));
INSERT INTO Users(userName,email,password) VALUES ('Monica Ellis','monica.ellis@gmail.com',md5('&%9bVxZN:^oO-)uhRJ4|f'));
INSERT INTO Users(userName,email,password) VALUES ('Doreen London','doreen.london@gmail.com',md5('rOn2_^@p30=qo%If9w<b.'));
INSERT INTO Users(userName,email,password) VALUES ('Sara Wyss','sara.wyss@gmail.com',md5('bD6%!n0Em\/g_*h+q-iMY'));
INSERT INTO Users(userName,email,password) VALUES ('Michael Thomas','michael.thomas@gmail.com',md5('eq3?k&sM-O\69;/uJyS=}B'));
INSERT INTO Users(userName,email,password) VALUES ('Juan Bilodeau','juan.bilodeau@gmail.com',md5('!Hr}Xu*TwAM{G[&;(Py2)'));
INSERT INTO Users(userName,email,password) VALUES ('Alexander Scott','alexander.scott@gmail.com',md5('|RWblmvSB2qJU}^g)-N~.O'));
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'Instant Pot Tomato and Beef Sauce', 'Side Dish', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5345297.jpg', '{"1 pound lean ground beef", "1 teaspoon salt", "1/2 teaspoon freshly ground black pepper", "1 large onion, finely diced", "4 cloves garlic, minced", "2 teaspoons Italian seasoning", "1/4 cup dry red wine", "1 (24 ounce) container crushed tomatoes", "1 (28 ounce) can whole peeled San Marzano tomatoes, crushed with a fork", "2 teaspoons lemon juice"}', 16.9, 17.3, 11, 4.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'Bren''s Italian Meatballs', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F3708702.jpg', '{"1/2 cup fresh bread crumbs", "1/2 cup grated pecorino Romano cheese", "2 large cloves garlic, minced", "1 tablespoon chopped fresh parsley", "1/4 teaspoon ground black pepper", "1 pinch red chili pepper flakes", "1 egg", "1 pound lean ground beef"}', 21.8, 3.6, 16.8, 0.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Bon Appetit''s Meatballs', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2490106.jpg', '{"1 1/2 pounds coarsely ground pork", "1 1/2 pounds sweet Italian sausage without fennel, casings removed", "1 1/2 pounds ground beef sirloin", "1 1/2 pounds ground beef chuck", "1/2 loaf day-old (hard) Italian bread, torn into chunks", "1 (32 ounce) carton low-sodium chicken broth", "1 whole head garlic, minced", "1 cup packed fresh Italian parsley leaves", "4 large eggs, beaten", "8 ounces Pecorino Romano cheese (such as Locatelli), grated", "1/4 cup extra-virgin olive oil", "2 tablespoons unsalted butter"}', 47, 21.5, 47.2, 1.2);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (6, 'Soft Zucchini Spice Cookies', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F8272918.jpg', '{"1/2 cup butter, softened", "1 cup packed brown sugar", "1 egg", "1 3/4 cups all-purpose flour", "2 teaspoons baking powder", "1/2 teaspoon salt", "3/4 teaspoon ground cinnamon", "1/4 teaspoon ground nutmeg", "1/8 teaspoon ground cloves", "1/4 cup milk", "1 1/2 cups grated zucchini", "1/2 cup chopped walnuts", "1/2 cup raisins", "1 teaspoon orange zest"}', 1, 9.6, 2.9, 5.5);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (7, 'Just Like Wendy''s Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6278897.jpg', '{"2 tablespoons olive oil", "2 pounds ground beef", "2 stalks celery, chopped", "1 onion, chopped", "1 green bell pepper, chopped", "3 (14 ounce) cans stewed tomatoes", "1 (10 ounce) can diced tomatoes with green chiles (such as RO*TEL)", "1 (14 ounce) can tomato sauce", "1 cup water", "2 (1.25 ounce) packages chili seasoning (such as McCormick Mild Chili Seasoning Mix)", "1 (14 ounce) can kidney beans, undrained", "1 (14 ounce) can pinto beans, undrained", " salt and ground black pepper to taste", "1 tablespoon white vinegar, or more to taste"}', 22.6, 28.8, 14.8, 8.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (8, 'Chocolate Zucchini Cookies', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1036633.jpg', '{"1/2 cup butter flavored shortening", "1/2 cup white sugar", "1/2 cup brown sugar", "1 egg", "1 teaspoon vanilla extract", "2 1/4 cups all-purpose flour", "1/3 cup unsweetened cocoa powder", "1 teaspoon baking soda", "1/2 teaspoon salt", "1 3/4 cups grated zucchini"}', 0.9, 8.5, 2.5, 3.7);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (16, 'My Favorite Sloppy Joes', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F994391.jpg', '{"1 pound lean ground beef", "1 cup ketchup", "1/4 cup dried minced onion", "3 tablespoons brown sugar, or to taste", "2 tablespoons spicy brown mustard", "1 tablespoon Worcestershire sauce, or more to taste", "1 tablespoon liquid smoke flavoring", "1 teaspoon minced garlic", "1 cup beef broth", " salt and ground black pepper to taste"}', 16.1, 19.6, 12, 16.9);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (17, 'Grandma''s Chocolate Zucchini Brownies', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2296609.jpg', '{"2 cups all-purpose flour", "2 tablespoons unsweetened cocoa powder", "1 teaspoon baking soda", "1/2 teaspoon salt", "1/2 cup butter", "1 1/2 cups white sugar", "2 eggs", "1 teaspoon vanilla extract", "2 1/2 cups shredded zucchini", "2 tablespoons white sugar", "1 cup chopped walnuts (Optional)   1 cup chocolate chips"}', 3.5, 32.8, 11.7, 21.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (19, 'Pork Rites (Taverns)', 'Meat and Poultry', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1114722.jpg', '{"2 pounds ground pork", "1 cup ketchup", "1/2 cup water", "2 tablespoons vinegar", "1 tablespoon brown sugar", "1 teaspoon dry mustard", "1 teaspoon salt", "12 hamburger buns"}', 17.5, 27.8, 13.2, 5.7);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (20, 'Loose Meat on a Bun, Restaurant Style', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F123542.jpg', '{"3 pounds ground beef", "1/4 cup minced onion", "3 tablespoons Worcestershire sauce", "4 cups beef broth", "1 teaspoon salt", "1 teaspoon ground black pepper", "2 teaspoons butter", "12 hamburger buns, split"}', 23.6, 22.9, 16.4, 0.6);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (23, 'Homemade Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F3953159.jpg', '{"2 tablespoons olive oil", "1 large onion, chopped", "2 cloves garlic, minced, or more to taste", "2 pounds lean ground beef", "2 (16 ounce) cans kidney beans, rinsed and drained", "1 (28 ounce) can diced tomatoes", "1 (15 ounce) can tomato puree", "1 cup water", "1 (4 ounce) can chopped green chile peppers", "2 tablespoons mild chili powder", "2 teaspoons salt", "2 teaspoons ground cumin", "1 teaspoon ground black pepper"}', 18.8, 19.6, 13.3, 4.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (24, 'Beer Burgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F620225.jpg', '{"1 pound ground beef", "1 small onion, finely chopped", "3 cloves garlic, minced", "1 tablespoon Worcestershire sauce", "1 teaspoon salt", "1/4 teaspoon ground black pepper", "1/4 cup beer"}', 19.5, 3.8, 13.7, 1.2);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (25, 'Sloppy Joe Sandwiches', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2296596.jpg', '{"1/2 pound ground beef", "1/2 onion, chopped", "1/2 cup ketchup", "2 tablespoons water", "1 tablespoon brown sugar", "1 teaspoon Worcestershire sauce", "1 teaspoon prepared mustard", "1 teaspoon white vinegar", "1 teaspoon chili powder", "1/4 teaspoon garlic powder", "1/4 teaspoon onion powder", "1/4 teaspoon salt", "2 hamburger buns, split"}', 24, 47.8, 20.3, 22);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (26, 'It''s Chili by George!!', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5243640.jpg', '{"2 pounds lean ground beef", "1 (46 fluid ounce) can tomato juice", "1 (29 ounce) can tomato sauce", "1 (15 ounce) can kidney beans, drained and rinsed", "1 (15 ounce) can pinto beans, drained and rinsed", "1 1/2 cups chopped onion", "1/4 cup chopped green bell pepper", "1/8 teaspoon ground cayenne pepper", "1/2 teaspoon white sugar", "1/2 teaspoon dried oregano", "1/2 teaspoon ground black pepper", "1 teaspoon salt", "1 1/2 teaspoons ground cumin", "1/4 cup chili powder"}', 22.3, 25.5, 13.7, 9.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (27, 'Juicy Lucy Burgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F995492.jpg', '{"1 1/2 pounds ground beef", "1 tablespoon Worcestershire sauce", "3/4 teaspoon garlic salt", "1 teaspoon black pepper", "4 slices American cheese (such as Kraft)", "4 hamburger buns, split"}', 38.1, 23.4, 37.5, 0.6);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (28, 'Instant Pot Chicken and Gravy', 'Meat and Poultry', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6996918.jpg', '{"3/4 teaspoon salt", "3/4 teaspoon paprika", "1/2 teaspoon thyme", "1/4 teaspoon ground black pepper", "1/4 teaspoon garlic powder", "1/8 teaspoon sage", "2 (10 ounce) boneless, skinless chicken breasts", "1 tablespoon olive oil", "1 cup chicken stock", " aluminum foil", "2 tablespoons cold water", "2 tablespoons cornstarch", "1 pinch salt and ground black pepper to taste"}', 59.8, 9.1, 14, 0.8);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (29, 'Instant Pot Chicken Congee', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6933650.jpg', '{"1 cup uncooked short-grain white rice", "1 tablespoon olive oil", "14 ounces boneless, skinless chicken breast", "6 cups chicken broth", "1 (2 inch) piece grated fresh ginger", "1 ear fresh corn, husked", " salt and ground black pepper to taste"}', 18.3, 32.5, 9.7, 2.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (31, 'Chris'' Bay Area Burger', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F407555.jpg', '{"1 pound ground beef", "2 cloves garlic, minced", "2 tablespoons extra virgin olive oil", "1 1/2 teaspoons salt", "1 teaspoon freshly ground black pepper", "1/2 teaspoon dried basil leaves", "4 hamburger buns, split"}', 22.9, 22.6, 6.8, 22.6);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (32, 'Danish Meatballs with Dill Sauce', 'Appetizers and Snacks', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F381832.jpg', '{"1 pound ground beef", "1/2 pound ground pork", "1/2 pound ground veal", "2 teaspoons salt", "1/2 teaspoon ground black pepper", "2 eggs", "1/3 cup finely chopped onion", "1/2 cup heavy cream", "1 cup dry bread crumbs", "1 cup butter", "1/4 cup all-purpose flour", "2 cups chicken broth", "2 cups sour cream", "1/4 cup chopped fresh dill"}', 16.9, 11.1, 37.6, 1.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (33, 'Spanish-Style Albondigas in a Sunny Mediterranean Sauce', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4559146.jpg', '{"3/4 pound ground beef", "1/4 pound ground pork", "2 tablespoons chopped spring onions", "2 tablespoons chopped fresh oregano", "1 clove garlic, finely chopped", "1 tablespoon Worcestershire sauce, or to taste", "1 tablespoon chopped fresh flat-leaf parsley", " salt and ground black pepper to taste", "1 2/3 cups fresh, white bread crumbs, divided", " extra-virgin olive oil for frying"}', 20.3, 31.2, 55.3, 6.5);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (34, 'Vegan Zucchini Brownies', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9158563.jpg', '{"cooking spray", "1 cup white sugar", "1/2 cup brown sugar", "1/2 cup olive oil", "1 tablespoon vanilla extract", "2 cups all-purpose flour", "1/2 cup cocoa powder (such as Hershey''s)", "1 1/2 teaspoons baking soda", "1 teaspoon salt", "3 cups shredded zucchini", "1 cup vegan chocolate chips"}', 2.9, 37.8, 10.6, 23.2);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (35, 'Italian Spaghetti Sauce with Meatballs', 'Side Dish', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5864844.jpg', '{"1 pound lean ground beef", "1 cup fresh bread crumbs", "1 tablespoon dried parsley", "1 tablespoon grated Parmesan cheese", "1/4 teaspoon ground black pepper", "1/8 teaspoon garlic powder", "1 egg, beaten"}', 18.9, 23, 21.2, 11.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (36, 'Healthier Sloppy Joes II', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F876321.jpg', '{"1 pound lean ground beef", "1/4 cup chopped onion", "1/4 cup chopped green bell pepper", "2 carrots, finely chopped", "2 cloves garlic, minced", "1 teaspoon prepared yellow mustard", "3/4 cup ketchup", "1 tablespoon brown sugar", "salt and ground black pepper to taste"}', 14.3, 13, 15.8, 10.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (37, 'Garlic and Onion Burgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1055214.jpg', '{"2 pounds ground beef", "1 tablespoon Worcestershire sauce", "3 cloves garlic, minced", "1/2 cup minced onion", "1 teaspoon salt", "1/2 teaspoon ground black pepper", "1 teaspoon Italian-style seasoning"}', 30.5, 3.1, 48.3, 1.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (40, 'Almost White Castle Hamburgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5248292.jpg', '{"1 1/2 pounds ground chuck", "1/3 cup plain bread crumbs", "1 egg", "1 (1 ounce) package dry onion soup mix", "2 tablespoons water", "1/2 teaspoon ground black pepper", "24 small square dinner rolls"}', 8.3, 16.4, 6.2, 1.7);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (42, 'Delicious Grilled Hamburgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F625104.jpg', '{"1 pound lean ground beef", "1 tablespoon Worcestershire sauce", "1 tablespoon liquid smoke flavoring", "1 teaspoon garlic powder", "1 tablespoon olive oil", " seasoned salt to taste"}', 28.2, 1.9, 30, 0.8);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (43, 'Spicy Zucchini Oatmeal Cookies', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1570056.jpg', '{"1 1/4 cups all-purpose flour", "1/2 teaspoon baking soda", "1 1/2 teaspoons ground cinnamon", "1/4 teaspoon ground cloves", "1/2 cup butter, softened", "2/3 cup packed brown sugar", "1 egg", "1 teaspoon vanilla extract", "1 cup quick cooking oats", "1 cup shredded zucchini", "1/2 cup raisins"}', 1.3, 12.8, 3.5, 6.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (44, 'Easy Slow Cooker Meatballs', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4528723.jpg', '{"1 1/2 pounds ground beef", "1 1/4 cups Italian seasoned bread crumbs", "1/4 cup chopped fresh parsley", "2 cloves garlic, minced", "1 medium yellow onion, chopped", "1 egg, beaten", "1 (28 ounce) jar spaghetti sauce", "1 (16 ounce) can crushed tomatoes", "1 (14.25 ounce) can tomato puree"}', 10.6, 18.2, 7.2, 6.2);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (46, 'Easy Homemade Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2905812.jpg', '{"1 pound ground beef", "1 onion, chopped", "1 (14.5 ounce) can stewed tomatoes", "1 (15 ounce) can tomato sauce", "1 (15 ounce) can kidney beans", "1 1/2 cups water", "1 pinch chili powder", "1 pinch garlic powder", " salt and pepper to taste"}', 30.6, 48.8, 9.2, 4.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (47, 'Boilermaker Tailgate Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F890638.jpg', '{"2 pounds ground beef chuck", "1 pound bulk Italian sausage", "3 (15 ounce) cans chili beans, drained", "1 (15 ounce) can chili beans in spicy sauce", "2 (28 ounce) cans diced tomatoes with juice", "1 (6 ounce) can tomato paste", "1 large yellow onion, chopped", "3 stalks celery, chopped", "1 green bell pepper, seeded and chopped", "1 red bell pepper, seeded and chopped", "2 green chile peppers, seeded and chopped", "1 tablespoon bacon bits", "4 cubes beef bouillon", "1/2 cup beer", "1/4 cup chili powder", "1 tablespoon Worcestershire sauce", "1 tablespoon minced garlic", "1 tablespoon dried oregano", "2 teaspoons ground cumin", "2 teaspoons hot pepper sauce (e.g. Tabasco™)", "1 teaspoon dried basil", "1 teaspoon salt", "1 teaspoon ground black pepper", "1 teaspoon cayenne pepper", "1 teaspoon paprika", "1 teaspoon white sugar", "1 (10.5 ounce) bag corn chips such as Fritos", "1 (8 ounce) package shredded Cheddar cheese"}', 30.8, 55.3, 30.1, 11.8);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (48, 'Quick Chili I', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F870042.jpg', '{"2 pounds ground beef", "1 onion, finely diced", "3 cloves garlic, minced", "1 (14.5 ounce) can diced tomatoes", "2 (14.5 ounce) cans diced tomatoes with green chile peppers", "1 (8 ounce) can tomato sauce", "1 cup water", "1 (15 ounce) can kidney beans", "1 (15 ounce) can pinto beans", "2 tablespoons chili powder", "1 tablespoon ground cumin", "2 tablespoons white sugar", "1 tablespoon salt", "1 teaspoon ground black pepper", "1 tablespoon hot pepper sauce"}', 25.6, 26.9, 31.3, 6.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (49, 'Picadillo', 'Meat and Poultry', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5504998.jpg', '{"2 tablespoons olive oil", "1 pound ground beef", "1/2 pound chorizo sausage, chopped", "1 large onion, chopped", "1/2 cup chopped red bell pepper", "2 cloves garlic, chopped", "1 tablespoon ground cumin", "2 teaspoons chili powder", "1 teaspoon dried oregano", "1 teaspoon paprika", "1/4 teaspoon cayenne pepper", "1/4 teaspoon ground cinnamon", "1 1/2 cups canned diced tomatoes", "3/4 cup beef stock", "1 tablespoon white sugar", "1/2 cup raisins", "1/4 cup chopped pimento-stuffed green olives", "2 tablespoons apple cider vinegar", "1 tablespoon capers, drained", "1/3 cup slivered almonds, toasted", "1 tablespoon lime juice"}', 25.5, 22.6, 32.7, 14.2);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (53, 'The Perfect Basic Burger', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2294328.jpg', '{"1 egg", "1/2 teaspoon salt", "1/2 teaspoon ground black pepper", "1 pound ground beef", "1/2 cup fine dry bread crumbs"}', 27.4, 10, 17.8, 0.9);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (54, 'Instant Pot Quick and Easy Outlaw Chili Beans', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4551168.jpg', '{"1 tablespoon vegetable oil", "1 1/2 pounds lean ground sirloin", "1 onion, diced", "3 stalks celery, diced", "4 cloves garlic, minced", "2 (15 ounce) cans chili beans, undrained", "1 (29 ounce) can pinto beans, rinsed and drained", "1 (29 ounce) can tomato sauce", "2 (4 ounce) cans diced green chiles, undrained", "2 tablespoons chili powder", "1 tablespoon cider vinegar", "1 tablespoon chile-garlic sauce (such as Huy Fong Foods), or to taste", "1 teaspoon dried oregano", "1/4 teaspoon ground cumin"}', 39.6, 62.1, 19.1, 13.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (55, 'Slow Cooker Chili II', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F196638.jpg', '{"1 pound ground beef", "3/4 cup diced onion", "3/4 cup diced celery", "3/4 cup diced green bell pepper", "2 cloves garlic, minced", "2 (10.75 ounce) cans tomato puree", "1 (15 ounce) can kidney beans with liquid", "1 (15 ounce) can kidney beans, drained", "1 (15 ounce) can cannellini beans with liquid", "1/2 tablespoon chili powder", "1/2 teaspoon dried parsley", "1 teaspoon salt", "3/4 teaspoon dried basil", "3/4 teaspoon dried oregano", "1/4 teaspoon ground black pepper", "1/8 teaspoon hot pepper sauce"}', 18.9, 33.4, 7.6, 4.9);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (56, 'Homemade Sloppy Joes', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F3793689.jpg', '{"1 1/2 pounds extra lean ground beef", "1/2 onion, diced", "2 cloves garlic, minced", "1 green pepper, diced", "1 cup water", "3/4 cup ketchup", "1 dash Worcestershire sauce", "2 tablespoons brown sugar", "1 teaspoon Dijon mustard", "1 1/2 teaspoons salt, or to taste", "1/2 teaspoon ground black pepper", "1 cup water", "1 pinch cayenne pepper to taste"}', 21.5, 14.4, 11.9, 12.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (58, 'The Twenty Dollar Burger', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9278800.jpg', '{"1 tablespoon butter", "1 small red onion, diced", "1 tablespoon minced garlic", "3/4 cup plain lowfat yogurt", "1 teaspoon salt", "1 teaspoon black pepper", "1 teaspoon cayenne pepper", "1 teaspoon mustard powder", "1 teaspoon garlic powder", "1 tablespoon horseradish", "1 tablespoon chopped fresh parsley", "1 tablespoon chopped fresh cilantro", "2 tablespoons Worcestershire sauce", "2 tablespoons low-sodium soy sauce", "1 tablespoon chipotle-flavored hot sauce", "2 pounds lean ground beef"}', 28, 6.5, 21, 3.7);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (60, 'Best Damn Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1060867.jpg', '{"4 tablespoons olive oil", "1 yellow onion, chopped", "1 red bell pepper, chopped", "1 Anaheim chile pepper, chopped", "2 red jalapeno pepper, chopped", "4 garlic cloves, minced", "2 1/2 pounds lean ground beef", "1/4 cup Worcestershire sauce", "1 pinch garlic powder, or to taste", "2 beef bouillon cubes", "1 (12 fluid ounce) can or bottle light beer (such as Coors)", "1 (28 ounce) can crushed San Marzano tomatoes", "1 (14.5 ounce) can fire-roasted diced tomatoes", "1 (12 ounce) can tomato paste", "1/2 cup white wine", "2 tablespoons chili powder", "2 tablespoons ground cumin", "1 tablespoon brown sugar", "1 tablespoon chipotle pepper sauce", "2 1/2 teaspoons dried basil", "1 1/2 teaspoons smoked paprika", "1 teaspoon salt", "1/2 teaspoon dried oregano", "1/2 teaspoon ground black pepper", "2 (16 ounce) cans dark red kidney beans (such as Bush''s)", "1 cup sour cream", "3 tablespoons chopped fresh cilantro", "1/2 teaspoon ground cumin"}', 25.2, 27.6, 21.1, 7.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'Zucchini-Coconut Cookie Bars', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5637451.jpg', '{"3/4 cup margarine, softened", "1/2 cup white sugar", "1/2 cup packed brown sugar", "2 eggs", "1 teaspoon vanilla extract", "1 3/4 cups all-purpose flour", "1/2 teaspoon salt", "1 1/2 teaspoons baking powder", "3/4 cup flaked coconut", "3/4 cup chopped pitted dates", "3/4 cup raisins", "2 cups grated zucchini", "1 tablespoon margarine, melted", "2 tablespoons milk", "1 teaspoon vanilla extract", "1/4 teaspoon ground cinnamon", "1 cup confectioners'' sugar", "1 cup finely chopped walnuts"}', 1.4, 15.1, 5.2, 10.2);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Margaret''s Keftedes (Greek Meatballs)', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F9273184.jpg', '{"4 slices white bread, torn into pieces", "2 tablespoons milk", "1 clove garlic", "1 onion, quartered", "4 teaspoons dried mint", "1 teaspoon salt", " ground black pepper to taste", "1/2 pound ground beef", "1/2 pound ground lamb", "4 eggs", "1/2 cup all-purpose flour for dredging", " vegetable oil for frying"}', 29.7, 28.6, 31.5, 3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (6, 'Slider-Style Mini Burgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6967288.jpg', '{"2 pounds ground beef", "1 (1.25 ounce) envelope onion soup mix", "1/2 cup mayonnaise", "2 cups shredded Cheddar cheese", "24 dinner rolls, split", "1/2 cup sliced pickles (Optional)"}', 12, 16.1, 13.2, 1.8);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'Christina''s Slow Cooker Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2032286.jpg', '{"3 pounds ground beef", "2 (14.5 ounce) cans diced tomatoes, or more to taste", "2 (6 ounce) cans tomato paste", "1/4 cup chili powder", "2 tablespoons dried oregano", "2 tablespoons ground cumin", "1 tablespoon chipotle pepper powder", "1 tablespoon cayenne pepper", "3 (14.5 ounce) cans kidney beans, rinsed and drained", "4 cups chopped onions", "4 cups chopped bell peppers", "3 jalapeno peppers, chopped", "2 cloves garlic, minced, or more to taste"}', 20.7, 24.4, 14.4, 6.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'My Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1726661.jpg', '{"2 pounds ground beef", "2 onions, chopped", "4 cloves garlic, minced", "2 tablespoons chili powder", "2 teaspoons salt", "2 teaspoons dried oregano", "4 (14.5 ounce) cans stewed tomatoes", "1 (15 ounce) can tomato sauce", "1 (15 ounce) can kidney beans with liquid"}', 24.9, 27.9, 31.2, 10.6);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'Frosted Zucchini Brownies', 'Fruits and Vegetables', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2606082.jpg', '{"2 cups white sugar", "1 1/2 cups canola oil", "4 large eggs", "2 cups all-purpose flour", "1/4 cup unsweetened cocoa powder", "2 teaspoons baking soda", "1 teaspoon ground cinnamon", "1 teaspoon salt", "1 teaspoon vanilla extract", "3 cups grated zucchini", "1 cup chopped nuts"}', 4.3, 45.3, 24.6, 33.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Instant Pot Red Thai Curry Chicken', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5299902.jpg', '{"1 tablespoon cooking oil", "2 tablespoons red curry paste, or more to taste", "1 1/2 pounds thin chicken breasts, cut into 1-inch strips", "1 (14 ounce) can unsweetened light coconut milk", "1 tablespoon fish sauce, or more to taste", "1 tablespoon palm sugar", "1 cup sliced yellow onion", "1 cup sliced red bell pepper", "1 cup sliced yellow bell pepper", "1 cup sliced orange bell pepper"}', 24.5, 20.4, 22, 6.5);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (6, 'Instant Pot Pork Chops', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6501901.jpg', '{"4 pork chops", "3 tablespoons butter", "1 (1 ounce) package dry onion soup mix (such as Lipton)", "1 cup apple juice"}', 14.9, 11.6, 13.1, 7.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (1, 'Chef John''s Turkey Sloppy Joes', 'Meat and Poultry', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1259534.jpg', '{"2 tablespoons butter", "1 onion, diced", " salt and ground black pepper to taste", "1 1/4 pounds ground turkey", "1/2 cup cold water", "3/4 cup ketchup", "1 1/2 tablespoons brown sugar", "1/2 teaspoon cayenne pepper, or to taste", "1/2 teaspoon Worcestershire sauce", "1/2 teaspoon unsweetened cocoa powder", "1 cup water, or as needed", "6 hamburger buns, split", "1/3 cup chopped green onions", "1/2 cup shredded white Cheddar cheese"}', 25.9, 36.8, 16.5, 11.9);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Instant Pot Pulled Pork Sandwiches', 'Side Dish', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5799283.jpg', '{"1 tablespoon smoked paprika", "1 1/2 teaspoons firmly packed light brown sugar", "1 teaspoon salt", "1/2 teaspoon ground black pepper", "2 pounds boneless pork loin roast, cut into 1-inch cubes", "1 tablespoon olive oil", "1 1/2 cups barbeque sauce", "1 cup water", "2 (12 count) packages Hawaiian bread rolls (such as King''s)"}', 55.6, 144.4, 5, 13.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Instant Pot Moroccan Chicken Tagine', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6741502.jpg', '{"2 tablespoons minced fresh garlic", "1 1/4 teaspoons paprika", "3/4 teaspoon ground ginger", "3/4 teaspoon ground turmeric", "1/8 teaspoon saffron powder", "1 1/2 pounds skinless, boneless chicken breasts, cut into bite-sized pieces", "1 preserved lemon", "2 tablespoons extra-virgin olive oil", "2 tablespoons butter", "2 medium red onions, sliced", "1 cinnamon stick", "1 cup pitted and halved Mediterranean olives", "1 cup chicken broth", "1 tablespoon chopped fresh flat-leaf parsley", "1 tablespoon chopped fresh cilantro"}', 24.6, 8.7, 13.8, 2.3);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Turkey and Rice Meatballs (Albondigas)', 'Meat and Poultry', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2941015.jpg', '{"1 pound ground turkey thigh meat", "1 cup packed, cooked white long grain rice", "3 cloves crushed garlic", "1/4 cup chopped Italian flat leaf parsley", "1 large egg", "2 teaspoons kosher salt", "1 teaspoon smoked paprika", "1 teaspoon ground cumin", "1/2 teaspoon freshly ground black pepper", "1/4 teaspoon dried oregano", "1/8 teaspoon cayenne pepper", "1 tablespoon olive oil"}', 19.1, 15.1, 14.3, 4.9);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Vegetarian Sloppy Joes', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F422585.jpg', '{"1/4 cup vegetable oil", "1/2 cup minced onion", "2 (8 ounce) packages tempeh", "1/2 cup minced green bell pepper", "2 cloves garlic, minced", "1/4 cup tomato sauce", "1 tablespoon vegetarian Worcestershire sauce", "1 tablespoon honey", "1 tablespoon blackstrap molasses", "1/4 teaspoon cayenne pepper", "1/4 teaspoon celery seed", "1/4 teaspoon ground cumin", "1/4 teaspoon salt", "1/2 teaspoon ground coriander", "1/2 teaspoon dried thyme", "1/2 teaspoon oregano", "1/2 teaspoon paprika", "1 pinch ground black pepper", " hamburger buns"}', 18.3, 37.3, 19.6, 8.8);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Teriyaki Chicken Meatballs', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4540170.jpg', '{"5 ounces ground chicken", "2 spring onions, chopped", "1 tablespoon sake (Japanese rice wine)", "1 tablespoon water", "1 tablespoon cornstarch", "1 1/2 teaspoons grated fresh ginger", "1 teaspoon soy sauce", "2 tablespoons vegetable oil, or more as needed", "4 shiitake mushrooms, cut in half", "1 3/4 ounces daikon (Japanese radish), sliced"}', 9.4, 10.7, 7.3, 6.9);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (5, 'Air Fryer Meatballs', 'Meat and Poultry', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F8096931.jpg', '{"16 ounces lean ground beef", "4 ounces ground pork", "1 teaspoon Italian seasoning", "1/2 teaspoon salt", "2 cloves garlic, minced", "1 egg", "1/2 cup grated Parmesan cheese", "1/3 cup Italian seasoned bread crumbs"}', 7.9, 2, 6.1, 0.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (6, 'Chef John''s Ricotta Meatballs', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1077229.jpg', '{"1/2 onion, minced", "2 tablespoons olive oil", "3 cloves garlic, minced", "1 pound ground beef", "1 cup whole milk ricotta cheese", "1/4 cup packed chopped Italian parsley", "1 egg, beaten", "1 1/2 teaspoons kosher salt", "1/2 teaspoon freshly ground black pepper", "1 pinch cayenne pepper, or to taste", "1/3 cup dry bread crumbs", "2 tablespoons olive oil", "1 (28 ounce) jar marinara sauce", "1 cup water"}', 16.3, 18.9, 20.9, 9.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (53, 'Authentic Cincinnati Chili', 'Soups, Stews and Chili Recipes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2746439.jpg', '{"2 pounds lean ground beef", "1 quart water, or amount to cover", "2 onions, finely chopped", "1 (15 ounce) can tomato sauce", "2 tablespoons vinegar", "2 teaspoons Worcestershire sauce", "4 cloves garlic, minced", "1/2 (1 ounce) square unsweetened chocolate", "1/4 cup chili powder", "1 1/2 teaspoons salt", "1 teaspoon ground cumin", "1 teaspoon ground cinnamon", "1/2 teaspoon ground cayenne pepper", "5 whole cloves", "5 whole allspice berries", "1 bay leaf"}', 19.1, 10.1, 12.6, 4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (53, 'Instant Pot Crispy Chicken Carnitas', 'World Cuisine', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6913262.jpg', '{"1 tablespoon ground cumin", "1/2 teaspoon chili powder", "1/2 teaspoon dried oregano", "1 pinch salt and ground black pepper to taste", "3 tablespoons olive oil, divided", "2 pounds skinless, boneless chicken breast halves", "5 cloves garlic, pressed", "1 yellow onion, quartered", "1/4 cup lime juice", "1/4 cup chicken broth", "1/2 bunch cilantro", "1 chipotle pepper in adobo sauce, or more to taste", "1 orange, zested and juiced", "1 bay leaf"}', 19.6, 4.7, 15.3, 1.6);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (53, 'Big Smokey Burgers', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4045578.jpg', '{"2 pounds ground beef sirloin", "1/2 onion, grated", "1 tablespoon grill seasoning", "1 tablespoon liquid smoke flavoring", "2 tablespoons Worcestershire sauce", "2 tablespoons minced garlic", "1 tablespoon adobo sauce from canned chipotle peppers", "1 chipotle chile in adobo sauce, chopped", " salt and pepper to taste", "6 (1 ounce) slices sharp Cheddar cheese (Optional)   6 hamburger buns"}', 38.7, 26.6, 29.7, 1.5);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (58, 'Unsloppy Joes', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F3379581.jpg', '{"1 tablespoon olive oil", "1/2 cup chopped onion", "1/2 cup chopped celery", "1/2 cup chopped carrots", "1/2 cup chopped green bell pepper", "1 clove garlic, minced", "1 (14.5 ounce) can diced tomatoes", "1 1/2 tablespoons chili powder", "1 tablespoon tomato paste", "1 tablespoon distilled white vinegar", "1 teaspoon ground black pepper", "1 (15 ounce) can kidney beans, drained and rinsed", "8 kaiser rolls"}', 7.8, 34.6, 3.9, 3.4);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (58, 'Hamburgers by Eddie', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2247628.jpg', '{"1 pound ground beef", "1 egg", "2 teaspoons minced garlic", "1 tablespoon steak sauce (e.g. A-1), or to taste"}', 20.6, 1.1, 31.4, 0.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (60, 'Melinda''s Porcupine Meatballs', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F3343759.jpg', '{"1 pound ground beef", "1/2 cup uncooked white rice", "1/2 cup water", "1/3 cup chopped onion", "1 teaspoon salt", "1/2 teaspoon celery salt", "1/8 teaspoon garlic powder", "1/8 teaspoon ground black pepper", "1 (15 ounce) can tomato sauce", "1 cup water, or more as needed", "2 teaspoons Worcestershire sauce"}', 22.2, 26.1, 13.7, 5.1);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (58, 'Andie''s Quick ''n Easy Sneaky Sloppy Joes', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4398244.jpg', '{"1 cup lentils", "2 onions, diced", "1 pound lean ground beef", "1 large green bell pepper, diced", "3/4 cup ketchup", "3/4 cup barbeque sauce", "1 tablespoon Worcestershire sauce", "1 tablespoon minced garlic"}', 18.2, 35.6, 7.4, 14.8);
INSERT INTO Recipes(chefID,recipeName,foodType,pictureUrl,ingredients,protein,carbs,fat,sugars) VALUES (60, 'Best Hamburger Ever', 'Main Dishes', 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5563136.jpg', '{"1 1/2 pounds lean ground beef", "1/2 onion, finely chopped", "1/2 cup shredded Colby Jack or Cheddar cheese", "1 teaspoon soy sauce", "1 teaspoon Worcestershire sauce", "1 egg", "1 (1 ounce) envelope dry onion soup mix", "1 clove garlic, minced", "1 tablespoon garlic powder", "1 teaspoon dried parsley", "1 teaspoon dried basil", "1 teaspoon dried oregano", "1/2 teaspoon crushed dried rosemary", " salt and pepper to taste"}', 39, 8.8, 27.5, 1.8);
INSERT INTO Bookmarks(userID,recipeID) VALUES (31, 42);
INSERT INTO Bookmarks(userID,recipeID) VALUES (31, 18);
INSERT INTO Bookmarks(userID,recipeID) VALUES (31, 21);
INSERT INTO Bookmarks(userID,recipeID) VALUES (30, 23);
INSERT INTO Bookmarks(userID,recipeID) VALUES (30, 10);
INSERT INTO Bookmarks(userID,recipeID) VALUES (30, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (2, 20);
INSERT INTO Bookmarks(userID,recipeID) VALUES (2, 43);
INSERT INTO Bookmarks(userID,recipeID) VALUES (2, 1);
INSERT INTO Bookmarks(userID,recipeID) VALUES (2, 31);
INSERT INTO Bookmarks(userID,recipeID) VALUES (52, 2);
INSERT INTO Bookmarks(userID,recipeID) VALUES (52, 53);
INSERT INTO Bookmarks(userID,recipeID) VALUES (39, 10);
INSERT INTO Bookmarks(userID,recipeID) VALUES (39, 57);
INSERT INTO Bookmarks(userID,recipeID) VALUES (39, 39);
INSERT INTO Bookmarks(userID,recipeID) VALUES (39, 55);
INSERT INTO Bookmarks(userID,recipeID) VALUES (39, 19);
INSERT INTO Bookmarks(userID,recipeID) VALUES (39, 1);
INSERT INTO Bookmarks(userID,recipeID) VALUES (38, 11);
INSERT INTO Bookmarks(userID,recipeID) VALUES (38, 15);
INSERT INTO Bookmarks(userID,recipeID) VALUES (38, 33);
INSERT INTO Bookmarks(userID,recipeID) VALUES (3, 1);
INSERT INTO Bookmarks(userID,recipeID) VALUES (3, 14);
INSERT INTO Bookmarks(userID,recipeID) VALUES (3, 39);
INSERT INTO Bookmarks(userID,recipeID) VALUES (3, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (3, 30);
INSERT INTO Bookmarks(userID,recipeID) VALUES (3, 20);
INSERT INTO Bookmarks(userID,recipeID) VALUES (12, 58);
INSERT INTO Bookmarks(userID,recipeID) VALUES (12, 35);
INSERT INTO Bookmarks(userID,recipeID) VALUES (12, 31);
INSERT INTO Bookmarks(userID,recipeID) VALUES (12, 12);
INSERT INTO Bookmarks(userID,recipeID) VALUES (18, 46);
INSERT INTO Bookmarks(userID,recipeID) VALUES (18, 23);
INSERT INTO Bookmarks(userID,recipeID) VALUES (18, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (18, 37);
INSERT INTO Bookmarks(userID,recipeID) VALUES (18, 33);
INSERT INTO Bookmarks(userID,recipeID) VALUES (21, 48);
INSERT INTO Bookmarks(userID,recipeID) VALUES (21, 18);
INSERT INTO Bookmarks(userID,recipeID) VALUES (21, 53);
INSERT INTO Bookmarks(userID,recipeID) VALUES (21, 29);
INSERT INTO Bookmarks(userID,recipeID) VALUES (29, 15);
INSERT INTO Bookmarks(userID,recipeID) VALUES (29, 26);
INSERT INTO Bookmarks(userID,recipeID) VALUES (29, 35);
INSERT INTO Bookmarks(userID,recipeID) VALUES (24, 1);
INSERT INTO Bookmarks(userID,recipeID) VALUES (24, 37);
INSERT INTO Bookmarks(userID,recipeID) VALUES (24, 42);
INSERT INTO Bookmarks(userID,recipeID) VALUES (14, 40);
INSERT INTO Bookmarks(userID,recipeID) VALUES (14, 56);
INSERT INTO Bookmarks(userID,recipeID) VALUES (14, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (14, 60);
INSERT INTO Bookmarks(userID,recipeID) VALUES (14, 31);
INSERT INTO Bookmarks(userID,recipeID) VALUES (8, 47);
INSERT INTO Bookmarks(userID,recipeID) VALUES (8, 55);
INSERT INTO Bookmarks(userID,recipeID) VALUES (8, 12);
INSERT INTO Bookmarks(userID,recipeID) VALUES (8, 38);
INSERT INTO Bookmarks(userID,recipeID) VALUES (8, 58);
INSERT INTO Bookmarks(userID,recipeID) VALUES (32, 52);
INSERT INTO Bookmarks(userID,recipeID) VALUES (32, 9);
INSERT INTO Bookmarks(userID,recipeID) VALUES (32, 58);
INSERT INTO Bookmarks(userID,recipeID) VALUES (25, 7);
INSERT INTO Bookmarks(userID,recipeID) VALUES (25, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (25, 46);
INSERT INTO Bookmarks(userID,recipeID) VALUES (44, 57);
INSERT INTO Bookmarks(userID,recipeID) VALUES (44, 23);
INSERT INTO Bookmarks(userID,recipeID) VALUES (49, 55);
INSERT INTO Bookmarks(userID,recipeID) VALUES (49, 11);
INSERT INTO Bookmarks(userID,recipeID) VALUES (49, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (28, 41);
INSERT INTO Bookmarks(userID,recipeID) VALUES (28, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (28, 46);
INSERT INTO Bookmarks(userID,recipeID) VALUES (28, 20);
INSERT INTO Bookmarks(userID,recipeID) VALUES (28, 37);
INSERT INTO Bookmarks(userID,recipeID) VALUES (28, 28);
INSERT INTO Bookmarks(userID,recipeID) VALUES (34, 20);
INSERT INTO Bookmarks(userID,recipeID) VALUES (34, 43);
INSERT INTO Bookmarks(userID,recipeID) VALUES (34, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (34, 37);
INSERT INTO Bookmarks(userID,recipeID) VALUES (34, 38);
INSERT INTO Bookmarks(userID,recipeID) VALUES (5, 17);
INSERT INTO Bookmarks(userID,recipeID) VALUES (5, 38);
INSERT INTO Bookmarks(userID,recipeID) VALUES (5, 9);
INSERT INTO Bookmarks(userID,recipeID) VALUES (5, 4);
INSERT INTO Bookmarks(userID,recipeID) VALUES (53, 54);
INSERT INTO Bookmarks(userID,recipeID) VALUES (53, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (53, 16);
INSERT INTO Bookmarks(userID,recipeID) VALUES (53, 15);
INSERT INTO Bookmarks(userID,recipeID) VALUES (10, 41);
INSERT INTO Bookmarks(userID,recipeID) VALUES (10, 11);
INSERT INTO Bookmarks(userID,recipeID) VALUES (10, 29);
INSERT INTO Bookmarks(userID,recipeID) VALUES (10, 21);
INSERT INTO Bookmarks(userID,recipeID) VALUES (10, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (10, 4);
INSERT INTO Bookmarks(userID,recipeID) VALUES (46, 12);
INSERT INTO Bookmarks(userID,recipeID) VALUES (46, 21);
INSERT INTO Bookmarks(userID,recipeID) VALUES (13, 18);
INSERT INTO Bookmarks(userID,recipeID) VALUES (13, 52);
INSERT INTO Bookmarks(userID,recipeID) VALUES (13, 22);
INSERT INTO Bookmarks(userID,recipeID) VALUES (45, 50);
INSERT INTO Bookmarks(userID,recipeID) VALUES (45, 57);
INSERT INTO Bookmarks(userID,recipeID) VALUES (45, 27);
INSERT INTO Bookmarks(userID,recipeID) VALUES (4, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (4, 46);
INSERT INTO Bookmarks(userID,recipeID) VALUES (4, 39);
INSERT INTO Bookmarks(userID,recipeID) VALUES (48, 24);
INSERT INTO Bookmarks(userID,recipeID) VALUES (48, 2);
INSERT INTO Bookmarks(userID,recipeID) VALUES (48, 49);
INSERT INTO Bookmarks(userID,recipeID) VALUES (48, 43);
INSERT INTO Bookmarks(userID,recipeID) VALUES (1, 4);
INSERT INTO Bookmarks(userID,recipeID) VALUES (1, 7);
INSERT INTO Bookmarks(userID,recipeID) VALUES (1, 20);
INSERT INTO Bookmarks(userID,recipeID) VALUES (1, 34);
INSERT INTO Bookmarks(userID,recipeID) VALUES (1, 13);
INSERT INTO Bookmarks(userID,recipeID) VALUES (59, 49);
INSERT INTO Bookmarks(userID,recipeID) VALUES (59, 26);
INSERT INTO Bookmarks(userID,recipeID) VALUES (36, 42);
INSERT INTO Bookmarks(userID,recipeID) VALUES (36, 13);
INSERT INTO Bookmarks(userID,recipeID) VALUES (36, 53);
INSERT INTO Bookmarks(userID,recipeID) VALUES (55, 51);
INSERT INTO Bookmarks(userID,recipeID) VALUES (55, 17);
INSERT INTO Bookmarks(userID,recipeID) VALUES (60, 50);
INSERT INTO Bookmarks(userID,recipeID) VALUES (60, 7);
INSERT INTO Bookmarks(userID,recipeID) VALUES (51, 51);
INSERT INTO Bookmarks(userID,recipeID) VALUES (51, 27);
INSERT INTO Bookmarks(userID,recipeID) VALUES (17, 51);
INSERT INTO Bookmarks(userID,recipeID) VALUES (17, 29);
INSERT INTO Bookmarks(userID,recipeID) VALUES (33, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (33, 52);
INSERT INTO Bookmarks(userID,recipeID) VALUES (33, 16);
INSERT INTO Bookmarks(userID,recipeID) VALUES (33, 57);
INSERT INTO Bookmarks(userID,recipeID) VALUES (33, 28);
INSERT INTO Bookmarks(userID,recipeID) VALUES (50, 34);
INSERT INTO Bookmarks(userID,recipeID) VALUES (50, 24);
INSERT INTO Bookmarks(userID,recipeID) VALUES (50, 47);
INSERT INTO Bookmarks(userID,recipeID) VALUES (50, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 34);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 46);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 10);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 60);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 54);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 23);
INSERT INTO Bookmarks(userID,recipeID) VALUES (40, 41);
INSERT INTO Bookmarks(userID,recipeID) VALUES (37, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (37, 13);
INSERT INTO Bookmarks(userID,recipeID) VALUES (37, 7);
INSERT INTO Bookmarks(userID,recipeID) VALUES (11, 40);
INSERT INTO Bookmarks(userID,recipeID) VALUES (11, 55);
INSERT INTO Bookmarks(userID,recipeID) VALUES (11, 13);
INSERT INTO Bookmarks(userID,recipeID) VALUES (11, 29);
INSERT INTO Bookmarks(userID,recipeID) VALUES (42, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (42, 11);
INSERT INTO Bookmarks(userID,recipeID) VALUES (42, 33);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 38);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 59);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 2);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 28);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 11);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (15, 5);
INSERT INTO Bookmarks(userID,recipeID) VALUES (26, 43);
INSERT INTO Bookmarks(userID,recipeID) VALUES (26, 45);
INSERT INTO Bookmarks(userID,recipeID) VALUES (26, 56);
INSERT INTO Bookmarks(userID,recipeID) VALUES (27, 5);
INSERT INTO Bookmarks(userID,recipeID) VALUES (27, 55);
INSERT INTO Bookmarks(userID,recipeID) VALUES (27, 56);
INSERT INTO Bookmarks(userID,recipeID) VALUES (27, 42);
INSERT INTO Bookmarks(userID,recipeID) VALUES (54, 49);
INSERT INTO Bookmarks(userID,recipeID) VALUES (22, 1);
INSERT INTO Bookmarks(userID,recipeID) VALUES (22, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (58, 10);
INSERT INTO Bookmarks(userID,recipeID) VALUES (58, 11);
INSERT INTO Bookmarks(userID,recipeID) VALUES (58, 47);
INSERT INTO Bookmarks(userID,recipeID) VALUES (58, 5);
INSERT INTO Bookmarks(userID,recipeID) VALUES (58, 16);
INSERT INTO Bookmarks(userID,recipeID) VALUES (9, 5);
INSERT INTO Bookmarks(userID,recipeID) VALUES (9, 12);
INSERT INTO Bookmarks(userID,recipeID) VALUES (9, 9);
INSERT INTO Bookmarks(userID,recipeID) VALUES (9, 22);
INSERT INTO Bookmarks(userID,recipeID) VALUES (6, 12);
INSERT INTO Bookmarks(userID,recipeID) VALUES (6, 22);
INSERT INTO Bookmarks(userID,recipeID) VALUES (35, 6);
INSERT INTO Bookmarks(userID,recipeID) VALUES (35, 53);
INSERT INTO Bookmarks(userID,recipeID) VALUES (43, 14);
INSERT INTO Bookmarks(userID,recipeID) VALUES (43, 24);
INSERT INTO Bookmarks(userID,recipeID) VALUES (20, 12);
INSERT INTO Bookmarks(userID,recipeID) VALUES (20, 33);
INSERT INTO Bookmarks(userID,recipeID) VALUES (7, 55);
INSERT INTO Bookmarks(userID,recipeID) VALUES (7, 25);
INSERT INTO Bookmarks(userID,recipeID) VALUES (23, 33);
INSERT INTO Bookmarks(userID,recipeID) VALUES (23, 40);
INSERT INTO Bookmarks(userID,recipeID) VALUES (23, 5);
INSERT INTO Bookmarks(userID,recipeID) VALUES (23, 23);
INSERT INTO Bookmarks(userID,recipeID) VALUES (57, 3);
INSERT INTO Bookmarks(userID,recipeID) VALUES (57, 32);
